// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart_Campus_PUMUB.Database.AppDbContext;

#nullable disable

namespace Smart_Campus_PUMUB.Database.Migrations
{
    [DbContext(typeof(SmartCampusDbContext))]
    partial class SmartCampusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Activity_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<string>("ActivityTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Activity_Title");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("ActivityId")
                        .HasName("PK__Activity__393F5A452A0468C9");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Book_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Book_Name");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category_Id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("BookId")
                        .HasName("PK__Book__C223F3B4A9366735");

                    b.HasIndex("CategoryId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Category_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Category_Name");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__6DB38D6EDD2875F1");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Department_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Department_Name");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("Faculty_Id");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__151675F14D7DCED4");

                    b.HasIndex("FacultyId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Faculty_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Faculty_Name");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("FacultyId")
                        .HasName("PK__Faculty__4EFCEAAADECD7578");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Grade_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GradeId");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Major_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("Faculty_Id");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Major_Name");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("MajorId")
                        .HasName("PK_Major");

                    b.HasIndex("FacultyId");

                    b.ToTable("Major");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.NewStudentAcc", b =>
                {
                    b.Property<int>("NewStudentAccId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NewStudentAccId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewStudentAccId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Full_Name");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RegisterAccId")
                        .HasColumnType("int")
                        .HasColumnName("RegisterAccId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NewStudentAccId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_NewStudentAcc_Username");

                    b.ToTable("NewStudentAcc");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.PaymentFee", b =>
                {
                    b.Property<int>("FeesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Fees_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeesId"));

                    b.Property<string>("ClassYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Class_Year");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FeeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Fee_Name");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<decimal>("MontlyAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Montly_Amount");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("FeesId")
                        .HasName("PK__Payment___24E61F7BD6034E00");

                    b.ToTable("Payment_Fees");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Permission_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Permission_Name");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Position_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Position_Name");

                    b.HasKey("PositionId")
                        .HasName("PK__Position__3C3EAE062191C9DE");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.RegisterAccount", b =>
                {
                    b.Property<int>("RegisterAccId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegisterAccId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterAccId"));

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ExamSeatNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Exam_Seat_No");

                    b.Property<string>("FormNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Form_No");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Full_Name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReviewedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("RegisterAccId");

                    b.ToTable("RegisterAcc");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.RegistrationPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Payment_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Amount_Paid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Payment_Date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Payment_Method");

                    b.Property<string>("ReceiptImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Receipt_Image");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("Registration_Id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("VerifyBy")
                        .HasColumnType("int");

                    b.HasKey("PaymentId")
                        .HasName("PK__Registra__DA6C7FC1C239E7F3");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("VerifyBy");

                    b.ToTable("Registration_Payment");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Role_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__D80AB4BB2E4B3432");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.RoleHierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAccessAllFaculties")
                        .HasColumnType("bit");

                    b.Property<int>("ChildRoleId")
                        .HasColumnType("int")
                        .HasColumnName("Child_Role_Id");

                    b.Property<int>("ParentRoleId")
                        .HasColumnType("int")
                        .HasColumnName("Parent_Role_Id");

                    b.HasKey("Id");

                    b.HasIndex("ChildRoleId");

                    b.HasIndex("ParentRoleId");

                    b.ToTable("RoleHierarchy");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Role_Permission_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("Permission_Id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("Role_Id");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Role_Permissions");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.RulesRegulation", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Rule_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Penalty")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("RuleId")
                        .HasName("PK__Rules_Re__70B7089E77C8C2C5");

                    b.ToTable("Rules_Regulations");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Semester_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Semester_Name");

                    b.Property<int?>("Sequence")
                        .HasColumnType("int")
                        .HasColumnName("Sequence");

                    b.HasKey("SemesterId")
                        .HasName("PK__Semester__12459A74A033FE51");

                    b.ToTable("Semester");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Student_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CurrentClassYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Current_Class_Year");

                    b.Property<string>("CurrentMajor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Current_Major");

                    b.Property<string>("CurrentRollNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Current_Roll_No");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EnrollmentNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Enrollment_No");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("Faculty_Id");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sem1_Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sem2_Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sem3_Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sem4_Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sem5_Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sem6_Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sem7_Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sem8_Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sem9_Result")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("StudentName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Student_Name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__A2F4E98C1185513A");

                    b.HasIndex("FacultyId");

                    b.HasIndex("UserId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.StudentPersonalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmissionSerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NewStudentAccId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("academic_year_level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("academic_year_range")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("admission_year")
                        .HasColumnType("int");

                    b.Property<string>("app_guardian_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("app_guardian_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("app_guardian_nrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("app_guardian_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("app_student_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("app_student_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("birth_place_region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blood_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("covid_vaccine_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("current_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ethnicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("exam_center")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("father_occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender_relation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guardian_address_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guardian_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guardian_occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guardian_relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("matric_passed_year")
                        .HasColumnType("int");

                    b.Property<string>("matric_roll_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mother_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mother_occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nrc_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nrc_state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nrc_township")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nrc_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("past_exam_major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("past_exam_roll_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("past_exam_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("past_exam_year")
                        .HasColumnType("int");

                    b.Property<string>("permanent_address_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permanent_address_mm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("previous_year_roll_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roll_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("stipend_requested")
                        .HasColumnType("bit");

                    b.Property<string>("student_name_en")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_name_mm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_nrc_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("university_reg_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentPersonalInfo");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.StudentRegistration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("registration_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<string>("AcademicYearLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("academic_year_level");

                    b.Property<string>("AcademicYearRange")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("academic_year_range");

                    b.Property<string>("AdmissionSerialNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("admission_serial_no");

                    b.Property<int?>("AdmissionYear")
                        .HasColumnType("int")
                        .HasColumnName("admission_year");

                    b.Property<string>("AppGuardianAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("app_guardian_address");

                    b.Property<string>("AppGuardianName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("app_guardian_name");

                    b.Property<string>("AppGuardianNrc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("app_guardian_nrc");

                    b.Property<string>("AppGuardianPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("app_guardian_phone");

                    b.Property<string>("AppStudentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("app_student_name");

                    b.Property<string>("AppStudentPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("app_student_phone");

                    b.Property<DateTime?>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("application_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("BirthPlaceRegion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("birth_place_region");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("blood_type");

                    b.Property<string>("CovidVaccineStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("covid_vaccine_status");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDatetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CurrentAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_address");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ethnicity");

                    b.Property<string>("ExamCenter")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("exam_center");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("father_name");

                    b.Property<string>("FatherOccupation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("father_occupation");

                    b.Property<string>("GenderRelation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gender_relation");

                    b.Property<string>("GuardianAddressPhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("guardian_address_phone");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("guardian_name");

                    b.Property<string>("GuardianOccupation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("guardian_occupation");

                    b.Property<string>("GuardianRelationship")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("guardian_relationship");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_delete");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("major");

                    b.Property<int>("MatricPassedYear")
                        .HasColumnType("int")
                        .HasColumnName("matric_passed_year");

                    b.Property<string>("MatricRollNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("matric_roll_no");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDatetime")
                        .HasColumnType("datetime")
                        .HasColumnName("modified_datetime");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mother_name");

                    b.Property<string>("MotherOccupation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("mother_occupation");

                    b.Property<string>("NationalityStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nationality_status");

                    b.Property<int?>("NewStudentAccId")
                        .HasColumnType("int")
                        .HasColumnName("NewStudentAccId");

                    b.Property<string>("PastExamMajor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("past_exam_major");

                    b.Property<string>("PastExamRollNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("past_exam_roll_no");

                    b.Property<string>("PastExamStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("past_exam_status");

                    b.Property<int?>("PastExamYear")
                        .HasColumnType("int")
                        .HasColumnName("past_exam_year");

                    b.Property<string>("PermanentAddressEn")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("permanent_address_en");

                    b.Property<string>("PermanentAddressMm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("permanent_address_mm");

                    b.Property<string>("Pob")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pob");

                    b.Property<string>("PreviousYearRollNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("previous_year_roll_no");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("religion");

                    b.Property<string>("RollNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("roll_no");

                    b.Property<string>("SignatureImage")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("signature_image");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<bool?>("StipendRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("stipend_requested");

                    b.Property<string>("StudentImage")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("student_image");

                    b.Property<string>("StudentNameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("student_name_en");

                    b.Property<string>("StudentNameMm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("student_name_mm");

                    b.Property<string>("StudentNrcNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("student_nrc_no");

                    b.Property<string>("UniversityRegNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("university_reg_no");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RegistrationId")
                        .HasName("PK__Student___22A298F6A8464C8B");

                    b.HasIndex("UserId");

                    b.ToTable("Student_Registrations");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.StudentSubjectEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Enrollment_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Enrollment_Date");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("Semester_Id");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("Student_Id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("Subject_Id");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "StudentId", "SubjectId", "SemesterId" }, "UQ_Student_Subject_Semester")
                        .IsUnique();

                    b.ToTable("Student_Subject_Enrollment");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.StudentSubjectResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Result_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("EnrollmentId")
                        .HasColumnType("int")
                        .HasColumnName("Enrollment_Id");

                    b.Property<string>("Grade")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsPass")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Pass");

                    b.Property<decimal?>("MarksObtained")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Marks_Obtained");

                    b.Property<decimal?>("MaxMarks")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Max_Marks");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("RegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("Registration_Id");

                    b.Property<DateTime?>("ResultDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Result_Date");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("Semester_Id");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("Student_Id");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("Subject_Id");

                    b.HasKey("ResultId");

                    b.HasIndex("EnrollmentId")
                        .IsUnique()
                        .HasFilter("[Enrollment_Id] IS NOT NULL");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "EnrollmentId" }, "IX_Result_Enrollment");

                    b.ToTable("Student_Subject_Result");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Subject_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("Faculty_Id");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("Semester_Id");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Subject_Code");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Subject_Name");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subject__D98F54B64787BB85");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SemesterId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.SubjectPrerequisite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("PrerequisiteSubjectId")
                        .HasColumnType("int")
                        .HasColumnName("Prerequisite_Subject_Id");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("Subject_Id");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisiteSubjectId");

                    b.HasIndex(new[] { "SubjectId", "PrerequisiteSubjectId" }, "UQ_Subject_Prereq")
                        .IsUnique();

                    b.ToTable("Subject_Prerequisite", t =>
                        {
                            t.HasCheckConstraint("CK_No_Self_Prereq", "[Subject_Id] <> [Prerequisite_Subject_Id]");
                        });
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tutor_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("Department_Id");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("Position_id");

                    b.Property<string>("Profile")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TutorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Tutor_Name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("TutorId")
                        .HasName("PK__Tutor__95664E0D409B1130");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tutor");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int")
                        .HasColumnName("Faculty_Id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Full_Name");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("MustChangePassword")
                        .HasColumnType("bit")
                        .HasColumnName("MustChangePassword");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("Role_id");

                    b.Property<string>("RoleNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Role_No");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__User__206D91702B22E388");

                    b.HasIndex("FacultyId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserName" }, "UQ__User__C9F28456D3FE7075")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Book", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Book__Category_I__5DCAEF64");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Department", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .IsRequired()
                        .HasConstraintName("FK__Departmen__Facul__59063A47");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Major", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Faculty", "Faculty")
                        .WithMany("Majors")
                        .HasForeignKey("FacultyId")
                        .IsRequired()
                        .HasConstraintName("FK_Major_Faculty");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.RegistrationPayment", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.StudentRegistration", "Registration")
                        .WithMany("RegistrationPayments")
                        .HasForeignKey("RegistrationId")
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__Regis__02084FDA");

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.User", "VerifyByNavigation")
                        .WithMany("RegistrationPayments")
                        .HasForeignKey("VerifyBy")
                        .HasConstraintName("FK__Registrat__Verif__02FC7413");

                    b.Navigation("Registration");

                    b.Navigation("VerifyByNavigation");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.RoleHierarchy", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Role", "ChildRole")
                        .WithMany()
                        .HasForeignKey("ChildRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Role", "ParentRole")
                        .WithMany()
                        .HasForeignKey("ParentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildRole");

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.RolePermission", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Student", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Student__User_Id__7C4F7684");

                    b.Navigation("Faculty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.StudentRegistration", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.User", "User")
                        .WithMany("StudentRegistrations")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Student_R__user___76969D2E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.StudentSubjectEnrollment", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.StudentSubjectResult", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.StudentSubjectEnrollment", "Enrollment")
                        .WithOne("Result")
                        .HasForeignKey("Smart_Campus_PUMUB.Database.AppDbContext.StudentSubjectResult", "EnrollmentId")
                        .HasConstraintName("FK_Result_Enrollment");

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.StudentRegistration", "Registration")
                        .WithMany("Results")
                        .HasForeignKey("RegistrationId");

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Semester", "Semester")
                        .WithMany()
                        .HasForeignKey("SemesterId");

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Student", "Student")
                        .WithMany("Results")
                        .HasForeignKey("StudentId");

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Subject", "Subject")
                        .WithMany("Results")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Enrollment");

                    b.Navigation("Registration");

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Subject", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Faculty", "Faculty")
                        .WithMany("Subjects")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK_Subject_Faculty");

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Semester", "Semester")
                        .WithMany("Subjects")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK__Subject__Semeste__628FA481");

                    b.Navigation("Faculty");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.SubjectPrerequisite", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Subject", "PrerequisiteSubject")
                        .WithMany("PrerequisiteFor")
                        .HasForeignKey("PrerequisiteSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Subject", "Subject")
                        .WithMany("Prerequisites")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrerequisiteSubject");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Tutor", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Department", "Department")
                        .WithMany("Tutors")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Tutor__Departmen__6EF57B66");

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Position", "Position")
                        .WithMany("Tutors")
                        .HasForeignKey("PositionId")
                        .IsRequired()
                        .HasConstraintName("FK__Tutor__Position___6E01572D");

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.User", "User")
                        .WithMany("Tutors")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Tutor__User_Id__6D0D32F4");

                    b.Navigation("Department");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.User", b =>
                {
                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Faculty", "Faculty")
                        .WithMany("Users")
                        .HasForeignKey("FacultyId")
                        .HasConstraintName("FK_User_Faculty");

                    b.HasOne("Smart_Campus_PUMUB.Database.AppDbContext.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__User__Role_id__68487DD7");

                    b.Navigation("Faculty");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Department", b =>
                {
                    b.Navigation("Tutors");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Faculty", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Majors");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Position", b =>
                {
                    b.Navigation("Tutors");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Semester", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.StudentRegistration", b =>
                {
                    b.Navigation("RegistrationPayments");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.StudentSubjectEnrollment", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.Subject", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("PrerequisiteFor");

                    b.Navigation("Prerequisites");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Smart_Campus_PUMUB.Database.AppDbContext.User", b =>
                {
                    b.Navigation("RegistrationPayments");

                    b.Navigation("StudentRegistrations");

                    b.Navigation("Students");

                    b.Navigation("Tutors");
                });
#pragma warning restore 612, 618
        }
    }
}
